######################## default configuration ####################
baseURL = "http://lautenbachrecycling.com/"
title = "Lautenbach Recycling"
theme = "bigspring"
languageName = "En"
languageCode = "en-us"
# post pagination
paginate = "3"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# google analytics
googleAnalytics = "" # example : UA-123-45
# unsafe html
[markup.goldmark.renderer]
unsafe = true

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"


############################## navigation ###############################

# main menu

[[menu.main]]
name = "About"
URL = "about"
weight = 1

[[menu.main]]
name = "Drop Boxes"
URL = "pricing"
weight = 2

[[menu.main]]
name = "Blog"
URL = "blog"
weight = 3

[[menu.main]]
name = "Contact"
URL = "contact"
weight = 4

[[menu.main]]
name = "FAQ"
URL = "faq"
weight = 5

# footer menu left
[[menu.footer_left]]
name = "About Us"
URL = "about"

[[menu.footer_left]]
name = "Contact Us"
URL = "contact"

[[menu.footer_left]]
name = "Careers"
URL = "#"


# footer menu middle
[[menu.footer_middle]]
name = "Drop Boxes"
URL = "pricing"

[[menu.footer_middle]]
name = "Demolition"
URL = "demolition"

[[menu.footer_middle]]
name = "Transportation"
URL = "transportation"

[[menu.footer_middle]]
name = "Self-Haul"
URL = "self-haul"

# footer menu right
[[menu.footer_right]]
name = "Privacy Policy"
URL = "privacy-policy"

[[menu.footer_right]]
name = "Make a Payment"
URL = "#"

[[menu.footer_right]]
name = "FAQ"
URL = "faq"

#################### default parameters ################################
[params]
logo = "images/logo2.svg"
logo_width = "200px"
# Meta data
description = "Lautenbach Recycling - Construction & Demolition Recycling, Sustainable Demolition, Green Building, Transportation, Organics Recycling, Waste Management Solutions and more"
author = "Lautenbach Recycling"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io

########### footer content ##########
footer_menu_left = "Company"
footer_menu_middle = "Services"
footer_menu_right = "Support"
footer_content = "A family owned business with a mission, Lautenbach Recycling has been leading the way in sustainable waste since 1991. [Learn More](/about/)"
# copyright
copyright = "Copyright 2020 Lautenbach Recycling <br> 13084 Ball Road, Mount Vernon, WA 98273"

# Preloader
[params.preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation buttons
[params.navigation_button]
enable = true
label = "Contact Us"
link = "contact"

  
############################# social site ########################
[[params.social]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "https://facebook.com/LautenbachRecycling"

[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "linkedin"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "#"